---
deployment:
  tasks:
    - export DEPLOYPATH=/home/herbertland/andyherbert.com/
    - /bin/cp -R .well-known $DEPLOYPATH
    - /bin/cp -R amazeing $DEPLOYPATH
    - /bin/cp -R documentationalism $DEPLOYPATH
    - /bin/cp -R engine $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R images_and_videos $DEPLOYPATH
    - /bin/cp -R javascript $DEPLOYPATH
    - /bin/cp -R other $DEPLOYPATH
    - /bin/cp -R portfolio $DEPLOYPATH
    - /bin/cp -R resume $DEPLOYPATH
    - /bin/cp -R sitemap $DEPLOYPATH
    - /bin/cp -R ‍ $DEPLOYPATH
    - /bin/cp 404.shtml $DEPLOYPATH
    - /bin/cp 401.shtml $DEPLOYPATH
    - /bin/cp 403.shtml $DEPLOYPATH
    - /bin/cp 400.shtml $DEPLOYPATH
    - /bin/cp 500.shtml $DEPLOYPATH
    - /bin/cp blog-archive.php $DEPLOYPATH
    - /bin/cp doc-template.html $DEPLOYPATH
    - /bin/cp error-style.css $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp getMenu.php $DEPLOYPATH
    - /bin/cp header.html $DEPLOYPATH
    - /bin/cp headerGet.js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp logo.png $DEPLOYPATH
    - /bin/cp oauth2.php $DEPLOYPATH
    - /bin/cp privacy.html $DEPLOYPATH
    - /bin/cp readPost.php $DEPLOYPATH
    - /bin/cp snowstorm.js $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH